//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusInspector.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspector
    {
        public Inspector()
        {
            this.Inspeccions = new HashSet<Inspeccion>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> dni { get; set; }
        public Nullable<decimal> legajo { get; set; }
        public Nullable<System.DateTime> FechaCarga { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
    
        public virtual ICollection<Inspeccion> Inspeccions { get; set; }
    }
}
