//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusInspector.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interno
    {
        public decimal id { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string Patente { get; set; }
        public Nullable<short> Año { get; set; }
        public Nullable<int> CantidadPasajeros { get; set; }
        public string Activo { get; set; }
    }
}
