//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusInspector.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BusInspectorEntities : DbContext
    {
        public BusInspectorEntities()
            : base("name=BusInspectorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Inspector> Inspectors { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<logs_tipo> logs_tipo { get; set; }
        public virtual DbSet<Inspeccion> Inspeccions { get; set; }
        public virtual DbSet<Seccion> Seccions { get; set; }
    
        public virtual ObjectResult<usuario_obtenerProductosDisponibles_Result> usuario_obtenerProductosDisponibles(Nullable<int> doc_tipo, string doc_nro)
        {
            var doc_tipoParameter = doc_tipo.HasValue ?
                new ObjectParameter("doc_tipo", doc_tipo) :
                new ObjectParameter("doc_tipo", typeof(int));
    
            var doc_nroParameter = doc_nro != null ?
                new ObjectParameter("doc_nro", doc_nro) :
                new ObjectParameter("doc_nro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usuario_obtenerProductosDisponibles_Result>("usuario_obtenerProductosDisponibles", doc_tipoParameter, doc_nroParameter);
        }
    
        public virtual ObjectResult<misavisos_obtener_u3_Result> misavisos_obtener_u3(Nullable<int> doc_tipo, string doc_numero)
        {
            var doc_tipoParameter = doc_tipo.HasValue ?
                new ObjectParameter("Doc_tipo", doc_tipo) :
                new ObjectParameter("Doc_tipo", typeof(int));
    
            var doc_numeroParameter = doc_numero != null ?
                new ObjectParameter("Doc_numero", doc_numero) :
                new ObjectParameter("Doc_numero", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<misavisos_obtener_u3_Result>("misavisos_obtener_u3", doc_tipoParameter, doc_numeroParameter);
        }
    }
}
