//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusInspector.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Observacion
    {
        public int id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> inspector { get; set; }
        public Nullable<int> seccion { get; set; }
        public string interno { get; set; }
        public string patente { get; set; }
    }
}
