//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusInspector.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoEntities : DbContext
    {
        public ProyectoEntities()
            : base("name=ProyectoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Inspeccion> Inspeccions { get; set; }
        public virtual DbSet<Inspector> Inspectors { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<logs_tipo> logs_tipo { get; set; }
        public virtual DbSet<Seccion> Seccions { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
