//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusInspector.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conductor
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Dni { get; set; }
        public Nullable<int> Legajo { get; set; }
        public Nullable<int> CodInspector { get; set; }
    
        public virtual Inspector Inspector { get; set; }
    }
}
