//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusInspector.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyContext : DbContext
    {
        public MyContext()
            : base("name=MyContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Conductor> Conductors { get; set; }
        public virtual DbSet<Inspeccion> Inspeccions { get; set; }
        public virtual DbSet<Inspector> Inspectors { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<logs_tipo> logs_tipo { get; set; }
        public virtual DbSet<Observacion> Observacions { get; set; }
        public virtual DbSet<Parada> Paradas { get; set; }
        public virtual DbSet<Seccion> Seccions { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
